### ISSUE TITLE
Notes Filters Not Working

### ISSUE THREAD

**Issue by rcamygit** [fccview/jotty#165]
The filter options appear to be working for me in Checklists and Tasks, but not in Notes. 

**Expected behavior:**
Select a Filter by type or Filter by category in All Notes view and have related notes displayed. 

**Actual behavior:**
I have 5 notes currently in Notes. They all have a category assigned and one of them is pinned. When I click the All button and go to All Notes only three notes are initially displayed. If I select the Items per page dropdown, which is initially not filled, and select any quantity all 5 notes become visible. 

I do see all my categories all the time. However only the first category seems to work. If I click any of the other categories nothing is displayed. 

Filter by type Recent shows all 5 notes. Filter by type Pinned does not show anything, including the one pinned note. 

**Environment:**
Proxmox server running Dockge in an LXC. Currently using the latest branch of Jotty. 

**Notes:**
This all works as anticipated with Tasks and Checklists.

**Comment by fccview** [comment]
> The filter options appear to be working for me in Checklists and Tasks, but not in Notes.
> 
> **Expected behavior:** Select a Filter by type or Filter by category in All Notes view and have related notes displayed.
> 
> **Actual behavior:** I have 5 notes currently in Notes. They all have a category assigned and one of them is pinned. When I click the All button and go to All Notes only three notes are initially displayed. If I select the Items per page dropdown, which is initially not filled, and select any quantity all 5 notes become visible.
> 
> I do see all my categories all the time. However only the first category seems to work. If I click any of the other categories nothing is displayed.
> 
> Filter by type Recent shows all 5 notes. Filter by type Pinned does not show anything, including the one pinned note.
> 
> **Environment:** Proxmox server running Dockge in an LXC. Currently using the latest branch of Jotty.
> 
> **Notes:** This all works as anticipated with Tasks and Checklists.

Hi,
Thank you for raising this, I'll get on it asap, just managed to replicate it ❤️

**Comment by fccview** [comment]
This has now been fixed in https://github.com/fccview/jotty/releases/tag/1.10.0 ❤️

**Comment by rcallison** [comment]
I updated to 1.10.0 tonight and I am still seeing an issue with the filters for All Notes.  It may be a different issue, and I can write a new post if you prefer, but it looks like the Filter by Category is only recognizing top level categories.  If I have a category nested below the top level the behavior is not correct.

For Instance I have a Clients category and underneath that I have another Category for Client 1.  When I go to All Notes I see all my notes with all categories listed.  If I click on the Clients filter I will see notes that have just the top level category, so this is correct.  If I select one of the filters for the sub Category, like Client 1, I do not see any notes.

The Filter by Type does appear to be working correctly.

**Comment by fccview** [comment]
> I updated to 1.10.0 tonight and I am still seeing an issue with the filters for All Notes.  It may be a different issue, and I can write a new post if you prefer, but it looks like the Filter by Category is only recognizing top level categories.  If I have a category nested below the top level the behavior is not correct.
> 
> For Instance I have a Clients category and underneath that I have another Category for Client 1.  When I go to All Notes I see all my notes with all categories listed.  If I click on the Clients filter I will see notes that have just the top level category, so this is correct.  If I select one of the filters for the sub Category, like Client 1, I do not see any notes.
> 
> The Filter by Type does appear to be working correctly.


Ouch! I'll get it sorted in the next release, sorry about this!

**Comment by fccview** [comment]
This should be now fixed in [1.10.1](https://github.com/fccview/jotty/releases/tag/1.10.1) ❤️ 
I have entirely refactored the way the filters work, so please let me know if it's all good for you now ❤️

**Comment by rcamygit** [comment]
Yes, all looks good in 1.10.1.  Filters look good for Checklists and Notes.
