### ISSUE TITLE
Some issues during the update to 1.10.0

### ISSUE THREAD

**Issue by vhsdream** [fccview/jotty#197]
Hi, I just wanted to share a couple of things that happened during my upgrade to 1.10.0. Please note, I'm using the [Proxmox Helper Script](https://community-scripts.github.io/ProxmoxVE/scripts?id=jotty) installation that I created and so I'm sure that is the main reason that the migration process is "stuck" the way it is.

OK, on to the list of issues:

- During the build of v1.10.0, the first time failed due to OOM. Up to now, having 3GB of RAM assigned to the LXC would suffice. I've had to bump that up to 4GB for the build to succeed now. Not the biggest deal, as once built I can reduce the RAM back down to 2GB or even 1.
- There was the following warning during build, which I don't recall seeing before:
```
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (2/14)  [==  ]
API Error: ew [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at eP (/opt/jotty/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:29225)
    at Module.eE (/opt/jotty/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:29561)
    at i (/opt/jotty/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34513)
    at Object.get (/opt/jotty/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34729)
    at x (/opt/jotty/.next/server/app/api/admin/rebuild-index/route.js:1:3525)
    at c (/opt/jotty/.next/server/app/api/user/route.js:1:1158)
    at /opt/jotty/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:41966
    at /opt/jotty/node_modules/next/dist/server/lib/trace/tracer.js:133:36
    at NoopContextManager.with (/opt/jotty/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/opt/jotty/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518) {
  digest: 'DYNAMIC_SERVER_USAGE'
```
The build still succeeded though, so perhaps it's possible to simply ignore that.
- Finally, on to the migration. I didn't need to worry about data loss since I wasn't sharing anything, but upon going to Jotty I was presented with the migration screen, so went ahead. Then I was given the message that everything succeeded:

<img width="960" height="540" alt="Image" src="https://github.com/user-attachments/assets/67ffd712-6d8c-4b8c-a048-3634d426d31c" />

But after this, there is no redirect to the main page, and if I refresh or change the URL in the address bar to the root, I just get redirected to the first migration page.

And if I check the filesystem, it appears as if there has been no migration:
```
root@todo:/opt/jotty/data# ls -la
total 29
drwxr-xr-x  7 root root   9 Nov  5 08:21 .
drwxr-xr-x 11 root root  29 Nov  5 08:20 ..
drwxr-xr-x  3 root root   3 Oct 21 15:33 checklists
drwxr-xr-x  3 root root   3 Oct 21 15:33 notes
-rw-r--r--  1 root root 234 Oct 21 15:33 settings.json
drwxr-xr-x  2 root root   3 Oct 28 10:02 sharing
-rw-r--r--  1 root root 994 Nov  5 08:34 site.webmanifest
drwxr-xr-x  3 root root   3 Oct 21 15:33 uploads
drwxr-xr-x  2 root root   5 Nov  5 08:22 users
root@todo:/opt/jotty/data# ls -la sharing/
total 10
drwxr-xr-x 2 root root  3 Oct 28 10:02 .
drwxr-xr-x 7 root root  9 Nov  5 08:21 ..
-rw-r--r-- 1 root root 37 Oct 28 10:05 shared-items.json
```
So, I'm wondering, what are the manual steps required for this migration? I'll need to update the helper script so that this process is done for the end users of the script.

**Comment by fccview** [comment]
Hey @vhsdream 
Thank you for sharing these! 

### migration
The migration should take that `shared-items.json` file and rename it to `shared-items.json.backup` and create two `.sharing.json` files within the notes/checklists folder.

Not sure why that's not working for you, do you have any logs when actually going through the migration in the backend? 
Wonder if there's some permission issues somewhere.

### OOM
I genuinely have no idea why it'd go out of memory, I have however installed a fairly heavy library that I will remove in 1.10.1 - there's a pull request for that, HOPEFULLY that should stop that OOM from happening, 4gb of memory to build it sounds insane btw, not sure why it'd take that much 🤯  I can look into it

p.s. you can already test the build without the package on the `develop` branch, just to see if my theory is correct.

### warnings
I have seen that warning, you can safely ignore it for now, I'll fix it on the new releases, some api endpoint i've added perform dynamic actions and nextjs doesn't like that and wants me to add a force-dynamic flag on them, it still allows it to work normally tho.

I'll programmatically add the flags on the next few releases as I improve the endpoints, sorry about these, users wouldn't normally see them as the image comes through as already built for docker, you can see the warning in the github actions of course.

Let's focus on the migration issue, another user had that because their sharing.json file was empty and I fixed it before releasing, so I'd be surprised if it's the same problem. Please let me know if you have any errors in the logs, that'd help.

**Comment by fccview** [comment]
Hey @vhsdream , what's in your `shared-items.json` file?
Wonder if you have something like `{"notes":{},"checklists":{}}` rather than it being actually empty?

If that's the issue I'll try and sort it out with the next 1.10.1

I have actually fixed that one scenario, I am almost certain that's what's going on with your situation.

Can you wait until pipeliens run here https://github.com/fccview/jotty/actions/runs/19104942088 and then test `develop` to see if both your OOM and migration issues are sorted? ❤️ 

_edit_

Actually you can test already, you don't need to wait for the pipeline on your proxmox environment do you 😛

**Comment by Osvaldo-Net** [comment]
Hi!
I’ve encountered the same issue during the migration process. This is my shared-items.json file, but when I click “Start Migration”, the interface seems to begin the process and then freezes on the “Migration Complete” screen (as shown in the attached image), without redirecting me anywhere afterward.

<img width="1919" height="803" alt="Image" src="https://github.com/user-attachments/assets/521acbe9-da55-4f88-9525-41f1ad7b2da6" />

<img width="964" height="120" alt="Image" src="https://github.com/user-attachments/assets/7409f921-549f-4d8f-98a0-f8a411774e02" />

**Comment by fccview** [comment]
> Hi! I’ve encountered the same issue during the migration process. This is my shared-items.json file, but when I click “Start Migration”, the interface seems to begin the process and then freezes on the “Migration Complete” screen (as shown in the attached image), without redirecting me anywhere afterward.
> 
> <img alt="Image" width="1919" height="803" src="https://private-user-images.githubusercontent.com/215711598/510171209-521acbe9-da55-4f88-9525-41f1ad7b2da6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIzNTI2ODksIm5iZiI6MTc2MjM1MjM4OSwicGF0aCI6Ii8yMTU3MTE1OTgvNTEwMTcxMjA5LTUyMWFjYmU5LWRhNTUtNGY4OC05NTI1LTQxZjFhZDdiMmRhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNVQxNDE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDE4NzY5MTk2ZTIxNDZlOGMzNzAwMTVlYjA1NTg4NjMwM2IxMzhlZDQ2MDM2ZDRiYTRhYzkwM2JhN2Q4NmZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlKF8Dgxncz-NSDZlxTZ9lKdOdepHMdDmBjADEihrII"> <img alt="Image" width="964" height="120" src="https://private-user-images.githubusercontent.com/215711598/510170805-7409f921-549f-4d8f-98a0-f8a411774e02.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIzNTI2ODksIm5iZiI6MTc2MjM1MjM4OSwicGF0aCI6Ii8yMTU3MTE1OTgvNTEwMTcwODA1LTc0MDlmOTIxLTU0OWYtNGQ4Zi05OGEwLWY4YTQxMTc3NGUwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwNVQxNDE5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWI0MDk5YjMwNGJjNTIwMzhmMjI3YTEyYzNiODM4MDFlZWRkN2VlYjE0YmY4ODdmYWMxZjM3ZDFjZjg0MDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XuvpCAls5_m9x9O6dLVESOsg4e793xTBAGPbLZyP2Oc">


BINGO! 
Yes, I have just sent a fix for _your_ scenario on `develop`, it'll be out with the next release, or you can wait for the pipeline (see my previous comment) to run and test on the `:develop` image ❤️

**Comment by vhsdream** [comment]
Yep, that's what my shared-items.json looks like too. I just tested and basically deleted that file and created empty `.sharing.json` files in `/notes` and `/checklists`, then restarted the service and I was able to get to the main page.

I've just rolled back my LXC and then shared some items, and now I'm updating to see if the migration works when there is data in the file.

Edit: I can confirm that the migration goes off perfectly when there are existing shared items 😸

**Comment by fccview** [comment]
> Yep, that's what my shared-items.json looks like too. I just tested and basically deleted that file and created empty `.sharing.json` files in `/notes` and `/checklists`, then restarted the service and I was able to get to the main page.
> 
> I've just rolled back my LXC and then shared some items, and now I'm updating to see if the migration works when there is data in the file.

Let me know if out of memory also gets sorted.
Lastly I have fixed the warnings, it was only two endpoints that were causing it, so you should get at least 2 out of 3 issues raised fixed with the next release ❤️

**Comment by fccview** [comment]
This should be now fixed in [1.10.1](https://github.com/fccview/jotty/releases/tag/1.10.1) ❤️ 
Feel free to close the issue when you confirm memory issue/logs are also sorted

**Comment by Osvaldo-Net** [comment]
From my side, the migration worked perfectly after the adjustment! Incredible job really, thank you so much!

**Comment by vhsdream** [comment]
The OOM issue is unfortunately still present; the update gets killed while it is linting:

```
yarn run v1.22.22
$ next build
   ▲ Next.js 14.0.4
   - Environments: .env

> [PWA] Compile server
> [PWA] Compile server
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: /opt/jotty/node_modules/next-pwa/register.js
> [PWA] Service worker: /opt/jotty/public/sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Linting and checking validity of types  .Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Again though, this is only going to be an issue for those running the Helper Script installation, and is easily remedied by increasing the RAM in the LXC. I wouldn't worry too much about it.

**Comment by fccview** [comment]
> The OOM issue is unfortunately still present; the update gets killed while it is linting:
> 
> ```
> yarn run v1.22.22
> $ next build
>    ▲ Next.js 14.0.4
>    - Environments: .env
> 
> > [PWA] Compile server
> > [PWA] Compile server
> > [PWA] Compile client (static)
> > [PWA] Auto register service worker with: /opt/jotty/node_modules/next-pwa/register.js
> > [PWA] Service worker: /opt/jotty/public/sw.js
> > [PWA]   url: /sw.js
> > [PWA]   scope: /
>  ✓ Creating an optimized production build
>  ✓ Compiled successfully
>    Linting and checking validity of types  .Killed
> error Command failed with exit code 137.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> Again though, this is only going to be an issue for those running the Helper Script installation, and is easily remedied by increasing the RAM in the LXC. I wouldn't worry too much about it.

Well kinda.. 4gb is a huge amount, I want to get to the bottom of it, it should NOT require that much, I think 3gb is also a stretch, I'll try to see what can be done to reduce the demand

**Comment by schneider-de-com** [comment]
Incidentally, 3 GB of RAM is sufficient for a new installation; an OOM only occurs during an update.

**Comment by fccview** [comment]
Most issues have been fixed on the  latest flag.
I will be looking into the OOM issue on update and the overall high memory need, but for now I'll close this one ♥️
